name: Build ROM

on:
  push:
    branches: [ master, followers ]
  pull_request:
  workflow_dispatch:

jobs:
  build_rom:
    name: Build ROM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install binutils-arm-none-eabi gcc-arm-none-eabi libpng-dev

      - name: Build & install agbcc
        run: |
          cd ..
          git clone --depth 1 https://github.com/pret/agbcc
          cd agbcc
          ./build.sh
          ./install.sh ../pokeemerald

      - name: Compile ROM
        run: |
          make modern

      - name: Upload ROM
        uses: actions/upload-artifact@v7
        with:
          name: pokeemerald
          path: '*.gba'
